### ISSUE TITLE
Does Jupyter-invoke enable different notebooks to have different endpoints?

### ISSUE THREAD

**Issue by Praxiteles** [EniramLtd/jupyter-invoke#4]
Jupyter Kernel Gateway only allows for one notebook to have an endpoint. 

Does Jupyter-invoke allow different notebooks to have different endpoints but all be accessible through GET or POST calls?

**Comment by jasaarim** [comment]
With Jupyter-invoke every GET call specifies the path to a notebook. There are no restrictions on the number of notebooks that are accessible. The only restriction is that each notebook can contain only one cell which returns the output for the GET call (all the cells are evaluated, though).
